import type { KasirkuDB } from './KasirkuDB';
import { registerMigrationsV001ToV020 } from './migrations/versions/v001-v020';
import { registerMigrationsV021ToV040 } from './migrations/versions/v021-v040';
import { registerMigrationsV041ToV060 } from './migrations/versions/v041-v060';
import { registerMigrationsV061ToV080 } from './migrations/versions/v061-v080';
import { registerMigrationsV081ToV098 } from './migrations/versions/v081-v098';
import { registerMigrationV099 } from './migrations/versions/v099';
import { registerMigrationV100 } from './migrations/versions/v100';
import { registerMigrationV101 } from './migrations/versions/v101';
import { registerMigrationV102 } from './migrations/versions/v102';
import { registerMigrationV103 } from './migrations/versions/v103';
import { registerMigrationV104 } from './migrations/versions/v104';
import { registerMigrationV105 } from './migrations/versions/v105';
import { registerMigrationV106 } from './migrations/versions/v106';
import { registerMigrationV107 } from './migrations/versions/v107';
import { registerMigrationV108 } from './migrations/versions/v108';
import { registerMigrationV109 } from './migrations/versions/v109';
import { registerMigrationV110 } from './migrations/versions/v110';
import { registerMigrationV112 } from './migrations/versions/v112';
import { registerMigrationV113 } from './migrations/versions/v113';
import { registerMigrationV114 } from './migrations/versions/v114';
import { registerMigrationV115 } from './migrations/versions/v115';
import { registerMigrationV116 } from './migrations/versions/v116';
import { registerMigrationV117 } from './migrations/versions/v117';
import { registerMigrationV118 } from './migrations/versions/v118';
import { registerMigrationV119 } from './migrations/versions/v119';
import { registerMigrationV120 } from './migrations/versions/v120';
import { registerMigrationV121 } from './migrations/versions/v121';
import { registerMigrationV122 } from './migrations/versions/v122';
import { registerMigrationV123 } from './migrations/versions/v123';
import { registerMigrationV124 } from './migrations/versions/v124';
import { registerMigrationV125 } from './migrations/versions/v125';
import { registerMigrationV126 } from './migrations/versions/v126';
import { registerMigrationV127 } from './migrations/versions/v127';
import { registerMigrationV128 } from './migrations/versions/v128';
import { registerMigrationV129 } from './migrations/versions/v129';

export function registerDatabaseMigrations(this: KasirkuDB) {
  registerMigrationsV001ToV020(this);
  registerMigrationsV021ToV040(this);
  registerMigrationsV041ToV060(this);
  registerMigrationsV061ToV080(this);
  registerMigrationsV081ToV098(this);
  registerMigrationV099(this);
  registerMigrationV100(this);
  registerMigrationV101(this);
  registerMigrationV102(this);
  registerMigrationV103(this);
  registerMigrationV104(this);
  registerMigrationV105(this);
  registerMigrationV106(this);
  registerMigrationV107(this);
  registerMigrationV108(this);
  registerMigrationV109(this);
  registerMigrationV110(this);
  registerMigrationV112(this);
  registerMigrationV113(this);
  registerMigrationV114(this);
  registerMigrationV115(this);
  registerMigrationV116(this);
  registerMigrationV117(this);
  registerMigrationV118(this);
  registerMigrationV119(this);
  registerMigrationV120(this);
  registerMigrationV121(this);
  registerMigrationV122(this);
  registerMigrationV123(this);
  registerMigrationV124(this);
  registerMigrationV125(this);
  registerMigrationV126(this);
  registerMigrationV127(this);
  registerMigrationV128(this);
  registerMigrationV129(this);
}
