import type {
  AccountingModuleActivationRule,
  AccountingProfileCode,
  AccountingProfileSetting,
  EnabledModule,
  IndustryExtensionCode,
} from '@/types';

export const ACCOUNTING_PROFILE_LABELS: Record<AccountingProfileCode, string> = {
  SAK_EMKM: 'SAK EMKM',
  SAK_EP: 'SAK EP',
  PSAK_FULL: 'PSAK Full',
  PSAP: 'PSAP',
  SAK_ETAP_LEGACY: 'SAK ETAP Legacy',
};

export const INDUSTRY_EXTENSION_LABELS: Record<IndustryExtensionCode, string> = {
  NONE: 'Tidak Ada',
  RETAIL: 'Retail',
  MANUFACTURING: 'Manufaktur',
  CONSTRUCTION: 'Konstruksi',
};

export const DEFAULT_ACCOUNTING_PROFILE_SETTING: AccountingProfileSetting = {
  id: 'default',
  accounting_profile: 'SAK_EMKM',
  industry_extension: 'RETAIL',
  template_id: 'default-sak-emkm-retail',
  locked_after_transaction: false,
  created_at: '',
  updated_at: '',
};

export const DEFAULT_ENABLED_MODULES: EnabledModule[] = [
  {
    id: 'CHART_OF_ACCOUNTS',
    code: 'CHART_OF_ACCOUNTS',
    is_enabled: true,
    source: 'SYSTEM',
    requires_profile: 'SAK_EMKM',
    requires_extension: 'RETAIL',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'CASH_FLOW_ACCOUNT_FILTER',
    code: 'CASH_FLOW_ACCOUNT_FILTER',
    is_enabled: true,
    source: 'SYSTEM',
    requires_profile: 'SAK_EMKM',
    requires_extension: 'RETAIL',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'ACCOUNT_TEMPLATES',
    code: 'ACCOUNT_TEMPLATES',
    is_enabled: true,
    source: 'SYSTEM',
    requires_profile: 'SAK_EMKM',
    requires_extension: 'RETAIL',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'GENERAL_LEDGER',
    code: 'GENERAL_LEDGER',
    is_enabled: false,
    source: 'SYSTEM',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'MANUFACTURING',
    code: 'MANUFACTURING',
    is_enabled: false,
    source: 'SYSTEM',
    requires_extension: 'MANUFACTURING',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'CONSTRUCTION',
    code: 'CONSTRUCTION',
    is_enabled: false,
    source: 'SYSTEM',
    requires_extension: 'CONSTRUCTION',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'PSAP_REPORTING',
    code: 'PSAP_REPORTING',
    is_enabled: false,
    source: 'SYSTEM',
    requires_profile: 'PSAP',
    requires_extension: 'NONE',
    created_at: '',
    updated_at: '',
  },
];

export const ACCOUNTING_MODULE_ACTIVATION_RULES: AccountingModuleActivationRule[] = [
  {
    id: 'SAK_EMKM-RETAIL-CHART_OF_ACCOUNTS',
    accounting_profile: 'SAK_EMKM',
    industry_extension: 'RETAIL',
    module_code: 'CHART_OF_ACCOUNTS',
    default_enabled: true,
    requires_confirmation: false,
    requires_data_safety_check: false,
    description: 'Daftar akun operasional untuk toko retail.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'SAK_EMKM-RETAIL-CASH_FLOW_ACCOUNT_FILTER',
    accounting_profile: 'SAK_EMKM',
    industry_extension: 'RETAIL',
    module_code: 'CASH_FLOW_ACCOUNT_FILTER',
    default_enabled: true,
    requires_confirmation: false,
    requires_data_safety_check: false,
    description: 'Filter dan grouping arus kas berdasarkan snapshot akun.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'SAK_EMKM-RETAIL-ACCOUNT_TEMPLATES',
    accounting_profile: 'SAK_EMKM',
    industry_extension: 'RETAIL',
    module_code: 'ACCOUNT_TEMPLATES',
    default_enabled: true,
    requires_confirmation: true,
    requires_data_safety_check: true,
    description: 'Template akun SAK EMKM retail ringan.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'SAK_EMKM-RETAIL-GENERAL_LEDGER',
    accounting_profile: 'SAK_EMKM',
    industry_extension: 'RETAIL',
    module_code: 'GENERAL_LEDGER',
    default_enabled: false,
    requires_confirmation: true,
    requires_data_safety_check: true,
    description: 'General ledger double-entry. Aktifkan setelah siap mulai posting dari tanggal cutoff.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'SAK_EP-MANUFACTURING-MANUFACTURING',
    accounting_profile: 'SAK_EP',
    industry_extension: 'MANUFACTURING',
    module_code: 'MANUFACTURING',
    default_enabled: false,
    requires_confirmation: true,
    requires_data_safety_check: true,
    description: 'Gate manufaktur. Tetap nonaktif sampai BOM, production order, costing, dan WIP movement tersedia.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'PSAK_FULL-MANUFACTURING-MANUFACTURING',
    accounting_profile: 'PSAK_FULL',
    industry_extension: 'MANUFACTURING',
    module_code: 'MANUFACTURING',
    default_enabled: false,
    requires_confirmation: true,
    requires_data_safety_check: true,
    description: 'Gate manufaktur PSAK Full. Tetap nonaktif sampai domain produksi lengkap.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'SAK_EP-CONSTRUCTION-CONSTRUCTION',
    accounting_profile: 'SAK_EP',
    industry_extension: 'CONSTRUCTION',
    module_code: 'CONSTRUCTION',
    default_enabled: false,
    requires_confirmation: true,
    requires_data_safety_check: true,
    description: 'Gate konstruksi. Tetap nonaktif sampai contract, progress billing, retensi, dan revenue recognition tersedia.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'PSAK_FULL-CONSTRUCTION-CONSTRUCTION',
    accounting_profile: 'PSAK_FULL',
    industry_extension: 'CONSTRUCTION',
    module_code: 'CONSTRUCTION',
    default_enabled: false,
    requires_confirmation: true,
    requires_data_safety_check: true,
    description: 'Gate konstruksi PSAK Full. Tetap nonaktif sampai domain proyek lengkap.',
    created_at: '',
    updated_at: '',
  },
  {
    id: 'PSAP-NONE-PSAP_REPORTING',
    accounting_profile: 'PSAP',
    industry_extension: 'NONE',
    module_code: 'PSAP_REPORTING',
    default_enabled: false,
    requires_confirmation: true,
    requires_data_safety_check: true,
    description: 'Gate report PSAP. Tetap nonaktif sampai mode pemerintahan dan report PSAP tersedia.',
    created_at: '',
    updated_at: '',
  },
];
