export const PRODUCT_CATEGORIES = [
  { value: 'bumbu', label: 'Bumbu & Bahan Masak' },
  { value: 'sembako', label: 'Sembako Inti' },
  { value: 'makanan_instan', label: 'Makanan Instan' },
  { value: 'snack', label: 'Snack & Makanan Ringan' },
  { value: 'minuman', label: 'Minuman' },
  { value: 'makanan_pembuka', label: 'Makanan Pembuka' },
  { value: 'makanan_utama', label: 'Makanan Utama' },
  { value: 'makanan_penutup', label: 'Makanan Penutup' },
  { value: 'minuman_dingin', label: 'Minuman Dingin' },
  { value: 'minuman_panas', label: 'Minuman Panas' },
  { value: 'kopi', label: 'Kopi' },
  { value: 'teh', label: 'Teh' },
  { value: 'jus_smoothie', label: 'Jus & Smoothie' },
  { value: 'bakery_pastry', label: 'Bakery & Pastry' },
  { value: 'paket_combo', label: 'Paket & Combo' },
  { value: 'topping_tambahan', label: 'Topping & Tambahan' },
  { value: 'household_cleaning', label: 'Household Cleaning' },
  { value: 'laundry', label: 'Laundry' },
  { value: 'personal_care', label: 'Personal Care' },
  { value: 'non_consumable', label: 'Non-consumable / General Goods' },
  { value: 'lainnya', label: 'Lain-lain' },
];

export type ProductCategoryValue = typeof PRODUCT_CATEGORIES[number]['value'];
