export const FINANCE_CATEGORIES = {
  SALES: 'PENJUALAN',
  AUTO_COGS: 'HPP_OTOMATIS',
  STOCK_PURCHASE: 'PEMBELIAN_STOK',
  WITHDRAWAL: 'PENARIKAN_SALDO',
  OPENING_BALANCE: 'SALDO_AWAL',
  OTHER: 'LAINNYA',
  DEPOSIT: 'DEPOSIT',
  CAPITAL_ADDITION: 'TAMBAHAN_MODAL',
  LOAN: 'PINJAMAN',
} as const;

export const NON_PROFIT_FINANCE_CATEGORIES = [
  FINANCE_CATEGORIES.SALES,
  FINANCE_CATEGORIES.AUTO_COGS,
  FINANCE_CATEGORIES.STOCK_PURCHASE,
  FINANCE_CATEGORIES.WITHDRAWAL,
  FINANCE_CATEGORIES.OPENING_BALANCE,
  FINANCE_CATEGORIES.DEPOSIT,
  FINANCE_CATEGORIES.CAPITAL_ADDITION,
  FINANCE_CATEGORIES.LOAN,
] as const;

export const isProfitAffectingFinanceTransaction = (type: string, category: string) => {
  return (
    type !== 'OPENING_BALANCE' &&
    !NON_PROFIT_FINANCE_CATEGORIES.includes(category as typeof NON_PROFIT_FINANCE_CATEGORIES[number])
  );
};
