import type { SalesDocumentConfig } from './index';

export const salesInvoiceConfig: SalesDocumentConfig = {
  type: 'SALES_INVOICE',
  title: 'Sales Invoice',
  titleKey: 'salesDocuments.type.salesInvoice',
  numberPrefix: 'SI',
  headerFields: [
    { name: 'contact_id', labelKey: 'salesDocuments.field.customer', type: 'contact' },
    { name: 'customer_name', labelKey: 'salesDocuments.field.customerName', type: 'text', required: true },
    { name: 'document_date', labelKey: 'salesDocuments.field.documentDate', type: 'date', required: true },
    { name: 'due_date', labelKey: 'salesDocuments.field.dueDate', type: 'date', required: true },
    { name: 'payment_status', labelKey: 'salesDocuments.field.paymentStatus', type: 'paymentStatus', required: true },
    { name: 'tax_id', labelKey: 'salesDocuments.field.tax', type: 'tax' },
    { name: 'department_id', labelKey: 'salesDocuments.field.department', type: 'department' },
    { name: 'project_id', labelKey: 'salesDocuments.field.project', type: 'project' },
    { name: 'notes', labelKey: 'salesDocuments.field.notes', type: 'textarea' },
  ],
  lineItemColumns: [
    { name: 'product_id', labelKey: 'salesDocuments.field.product' },
    { name: 'quantity', labelKey: 'salesDocuments.field.quantity', editable: true },
    { name: 'unit', labelKey: 'salesDocuments.field.unit', editable: true },
    { name: 'price', labelKey: 'salesDocuments.field.price', editable: true },
    { name: 'discount_amount', labelKey: 'salesDocuments.field.discount', editable: true },
    { name: 'subtotal', labelKey: 'salesDocuments.field.subtotal' },
  ],
  summaryFields: [
    { name: 'subtotal_amount', labelKey: 'salesDocuments.field.subtotal' },
    { name: 'discount_amount', labelKey: 'salesDocuments.field.documentDiscount' },
    { name: 'tax_amount', labelKey: 'salesDocuments.field.tax' },
    { name: 'total_amount', labelKey: 'salesDocuments.field.total' },
  ],
  requiredFields: ['customer_name', 'document_date', 'due_date', 'payment_status'],
  behavior: {
    affectsStock: false,
    hasPricing: true,
    hasTax: true,
    hasDueDate: true,
    hasPaymentStatus: true,
    validateStock: false,
    allowContactPicker: true,
    allowDepartmentPicker: true,
    allowProjectPicker: true,
  },
};
