use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct AccountingPeriodDto {
    pub id: String,
    pub name: String,
    pub period_type: String,
    pub start_date: String,
    pub end_date: String,
    pub status: String,
    pub locked_at: Option<String>,
    pub locked_by: Option<String>,
    pub locked_by_name: Option<String>,
    pub closed_at: Option<String>,
    pub closed_by: Option<String>,
    pub closed_by_name: Option<String>,
    pub closing_journal_entry_id: Option<String>,
    pub reopened_at: Option<String>,
    pub reopened_by: Option<String>,
    pub reopened_by_name: Option<String>,
    pub reopen_reason: Option<String>,
    pub notes: Option<String>,
    pub version: i32,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
}
