use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct ClosingRunDto {
    pub id: String,
    pub period_id: String,
    pub period_name: String,
    pub start_date: String,
    pub end_date: String,
    pub status: String,
    pub retained_earning_account_id: String,
    pub retained_earning_account_code: String,
    pub retained_earning_account_name: String,
    pub net_income_amount: f64,
    pub total_revenue_amount: f64,
    pub total_contra_revenue_amount: f64,
    pub total_expense_amount: f64,
    pub closing_journal_entry_id: Option<String>,
    pub posted_at: Option<String>,
    pub reversed_at: Option<String>,
    pub reversed_by: Option<String>,
    pub reversed_by_name: Option<String>,
    pub reversal_journal_entry_id: Option<String>,
    pub reversal_reason: Option<String>,
    pub notes: Option<String>,
    pub version: i32,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
}
