use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct CooperativeMemberDto {
    pub id: String,
    pub member_number: String,
    pub name: String,
    pub identity_number: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub area_id: Option<String>,
    pub area_name: Option<String>,
    pub area_code: Option<String>,
    pub officer_id: Option<String>,
    pub officer_name: Option<String>,
    pub officer_position: Option<String>,
    pub join_date: String,
    pub status: String,
    pub notes: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct CooperativeSavingTransactionDto {
    pub id: String,
    pub member_id: String,
    pub member_number: String,
    pub member_name: String,
    pub saving_type: String,
    pub transaction_type: String,
    pub amount: f64,
    pub transaction_date: String,
    pub status: String,
    pub cash_account_id: Option<String>,
    pub cash_account_code: Option<String>,
    pub cash_account_name: Option<String>,
    pub payment_method: Option<String>,
    pub payment_channel: Option<String>,
    pub finance_transaction_id: Option<String>,
    pub journal_entry_id: Option<String>,
    pub reversal_of_transaction_id: Option<String>,
    pub reversal_transaction_id: Option<String>,
    pub reversal_finance_transaction_id: Option<String>,
    pub reversal_journal_entry_id: Option<String>,
    pub reversed_at: Option<String>,
    pub reversal_reason: Option<String>,
    pub notes: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct CooperativeMemberSavingBalanceDto {
    pub id: String,
    pub member_id: String,
    pub member_number: String,
    pub member_name: String,
    pub saving_type: String,
    pub balance: f64,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct CooperativeLoanDto {
    pub id: String,
    pub loan_number: String,
    pub member_id: String,
    pub member_number: String,
    pub member_name: String,
    pub principal_amount: f64,
    pub interest_rate_per_month: f64,
    pub tenor_months: i32,
    pub interest_calculation_type: String,
    pub billing_frequency: String,
    pub installment_count: i32,
    pub loan_service_rate: f64,
    pub loan_service_amount: f64,
    pub admin_fee_rate: f64,
    pub admin_fee_amount: f64,
    pub mandatory_saving_rate: f64,
    pub mandatory_saving_amount: f64,
    pub deduction_method: String,
    pub net_disbursement_amount: f64,
    pub total_interest_amount: f64,
    pub total_payable_amount: f64,
    pub outstanding_principal_amount: f64,
    pub outstanding_interest_amount: f64,
    pub outstanding_penalty_amount: f64,
    pub status: String,
    pub application_date: String,
    pub approved_at: Option<String>,
    pub approved_by: Option<String>,
    pub approved_by_name: Option<String>,
    pub approval_notes: Option<String>,
    pub rejected_at: Option<String>,
    pub rejected_by: Option<String>,
    pub rejected_by_name: Option<String>,
    pub rejection_reason: Option<String>,
    pub disbursed_at: Option<String>,
    pub officer_id: Option<String>,
    pub officer_name: Option<String>,
    pub officer_position: Option<String>,
    pub area_id: Option<String>,
    pub area_name: Option<String>,
    pub area_code: Option<String>,
    pub collection_schedule_id: Option<String>,
    pub collection_weekday: Option<i32>,
    pub cash_account_id: Option<String>,
    pub cash_account_code: Option<String>,
    pub cash_account_name: Option<String>,
    pub payment_method: Option<String>,
    pub payment_channel: Option<String>,
    pub finance_transaction_id: Option<String>,
    pub journal_entry_id: Option<String>,
    pub disbursement_notes: Option<String>,
    pub notes: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct CooperativeLoanInstallmentDto {
    pub id: String,
    pub loan_id: String,
    pub loan_number: String,
    pub member_id: String,
    pub member_number: String,
    pub member_name: String,
    pub installment_number: i32,
    pub due_date: String,
    pub principal_amount: f64,
    pub interest_amount: f64,
    pub penalty_amount: f64,
    pub paid_principal_amount: f64,
    pub paid_interest_amount: f64,
    pub paid_penalty_amount: f64,
    pub status: String,
    pub paid_at: Option<String>,
    pub collection_status: Option<String>,
    pub follow_up_date: Option<String>,
    pub collection_notes: Option<String>,
    pub last_contacted_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct CooperativeLoanPaymentDto {
    pub id: String,
    pub payment_number: String,
    pub payment_type: Option<String>,
    pub loan_id: String,
    pub loan_number: String,
    pub installment_id: Option<String>,
    pub member_id: String,
    pub member_number: String,
    pub member_name: String,
    pub amount: f64,
    pub principal_amount: f64,
    pub interest_amount: f64,
    pub penalty_amount: f64,
    pub payment_date: String,
    pub status: String,
    pub cash_account_id: Option<String>,
    pub cash_account_code: Option<String>,
    pub cash_account_name: Option<String>,
    pub payment_method: Option<String>,
    pub payment_channel: Option<String>,
    pub collector_id: Option<String>,
    pub collector_name: Option<String>,
    pub collector_position: Option<String>,
    pub received_by: Option<String>,
    pub received_by_name: Option<String>,
    pub posted_at: Option<String>,
    pub finance_transaction_id: Option<String>,
    pub journal_entry_id: Option<String>,
    pub reversal_of_payment_id: Option<String>,
    pub reversal_payment_id: Option<String>,
    pub reversal_finance_transaction_id: Option<String>,
    pub reversal_journal_entry_id: Option<String>,
    pub reversed_at: Option<String>,
    pub reversal_reason: Option<String>,
    pub notes: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
}
