use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct FixedAssetDto {
    pub id: String,
    pub asset_code: String,
    pub name: String,
    pub category: String,
    pub location: Option<String>,
    pub description: Option<String>,
    pub registration_type: String,
    pub acquisition_date: String,
    pub available_for_use_date: String,
    pub acquisition_cost: f64,
    pub residual_value: f64,
    pub useful_life_months: i32,
    pub depreciation_method: String,
    pub depreciation_start_date: String,
    pub regular_depreciation_amount: f64,
    pub opening_balance_date: Option<String>,
    pub opening_accumulated_depreciation: f64,
    pub opening_remaining_useful_life_months: Option<i32>,
    pub asset_account_id: String,
    pub asset_account_code: String,
    pub asset_account_name: String,
    pub accumulated_depreciation_account_id: String,
    pub accumulated_depreciation_account_code: String,
    pub accumulated_depreciation_account_name: String,
    pub depreciation_expense_account_id: String,
    pub depreciation_expense_account_code: String,
    pub depreciation_expense_account_name: String,
    pub department_id: Option<String>,
    pub department_code: Option<String>,
    pub department_name: Option<String>,
    pub project_id: Option<String>,
    pub project_code: Option<String>,
    pub project_name: Option<String>,
    pub is_active: bool,
    pub version: i32,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct FixedAssetDepreciationRunDto {
    pub id: String,
    pub run_number: String,
    pub period_id: String,
    pub period_name: String,
    pub period_start: String,
    pub period_end: String,
    pub posting_date: String,
    pub status: String,
    pub asset_count: i32,
    pub total_depreciation: f64,
    pub journal_entry_id: Option<String>,
    pub reversal_journal_entry_id: Option<String>,
    pub reversal_reason: Option<String>,
    pub notes: Option<String>,
    pub version: i32,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub posted_by: Option<String>,
    pub posted_by_name: Option<String>,
    pub posted_at: Option<String>,
    pub reversed_by: Option<String>,
    pub reversed_by_name: Option<String>,
    pub reversed_at: Option<String>,
    pub created_at: String,
    pub updated_at: String,
    pub deleted_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct FixedAssetDepreciationRunLineDto {
    pub id: String,
    pub run_id: String,
    pub asset_id: String,
    pub asset_code: String,
    pub asset_name: String,
    pub asset_category: String,
    pub acquisition_cost: f64,
    pub residual_value: f64,
    pub regular_depreciation_amount: f64,
    pub opening_accumulated_depreciation: f64,
    pub opening_book_value: f64,
    pub depreciation_amount: f64,
    pub closing_accumulated_depreciation: f64,
    pub closing_book_value: f64,
    pub asset_account_id: String,
    pub asset_account_code: String,
    pub asset_account_name: String,
    pub accumulated_depreciation_account_id: String,
    pub accumulated_depreciation_account_code: String,
    pub accumulated_depreciation_account_name: String,
    pub depreciation_expense_account_id: String,
    pub depreciation_expense_account_code: String,
    pub depreciation_expense_account_name: String,
    pub department_id: Option<String>,
    pub department_code: Option<String>,
    pub department_name: Option<String>,
    pub project_id: Option<String>,
    pub project_code: Option<String>,
    pub project_name: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FixedAssetDepreciationRunBundleDto {
    pub run: FixedAssetDepreciationRunDto,
    pub lines: Vec<FixedAssetDepreciationRunLineDto>,
}
