use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct SalesDocumentDto {
    pub id: String,
    pub document_number: String,
    pub r#type: String,
    pub status: String,
    pub contact_id: Option<String>,
    pub customer_name: String,
    pub customer_phone: Option<String>,
    pub customer_email: Option<String>,
    pub customer_address: Option<String>,
    pub customer_company_name: Option<String>,
    pub customer_tax_number: Option<String>,
    pub department_id: Option<String>,
    pub department_code: Option<String>,
    pub department_name: Option<String>,
    pub project_id: Option<String>,
    pub project_code: Option<String>,
    pub project_name: Option<String>,
    pub document_date: String,
    pub expired_at: Option<String>,
    pub due_date: Option<String>,
    pub warehouse_id: Option<String>,
    pub warehouse_code: Option<String>,
    pub warehouse_name: Option<String>,
    pub source_document_id: Option<String>,
    pub source_document_number: Option<String>,
    pub source_document_type: Option<String>,
    pub currency_code: Option<String>,
    pub currency_name: Option<String>,
    pub currency_symbol: Option<String>,
    pub base_currency_code: Option<String>,
    pub exchange_rate: Option<f64>,
    pub exchange_rate_source: Option<String>,
    pub exchange_rate_basis: Option<String>,
    pub exchange_rate_date: Option<String>,
    pub subtotal_amount: Option<f64>,
    pub foreign_subtotal_amount: Option<f64>,
    pub discount_type: Option<String>,
    pub discount_value: Option<f64>,
    pub discount_amount: Option<f64>,
    pub foreign_discount_amount: Option<f64>,
    pub discount_account_id: Option<String>,
    pub discount_account_code: Option<String>,
    pub discount_account_name: Option<String>,
    pub tax_id: Option<String>,
    pub tax_name: Option<String>,
    pub tax_code: Option<String>,
    pub tax_rate: Option<f64>,
    pub tax_calculation_mode: Option<String>,
    pub tax_amount: Option<f64>,
    pub foreign_tax_amount: Option<f64>,
    pub total_amount: Option<f64>,
    pub foreign_total_amount: Option<f64>,
    pub payment_status: Option<String>,
    pub paid_amount: Option<f64>,
    pub paid_at: Option<String>,
    pub payment_method: Option<String>,
    pub cash_account_id: Option<String>,
    pub cash_account_code: Option<String>,
    pub cash_account_name: Option<String>,
    pub finance_transaction_id: Option<String>,
    pub notes: Option<String>,
    pub issued_at: Option<String>,
    pub voided_at: Option<String>,
    pub void_reason: Option<String>,
    pub version: i32,
    pub created_by: Option<String>,
    pub created_by_name: Option<String>,
    pub updated_by: Option<String>,
    pub updated_by_name: Option<String>,
    pub created_at: String,
    pub updated_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct SalesDocumentItemDto {
    pub id: String,
    pub document_id: String,
    pub product_id: String,
    pub product_name: String,
    pub sku: Option<String>,
    pub unit: String,
    pub quantity: f64,
    pub ordered_quantity: Option<f64>,
    pub delivered_quantity: Option<f64>,
    pub price: Option<f64>,
    pub currency_code: Option<String>,
    pub exchange_rate: Option<f64>,
    pub exchange_rate_source: Option<String>,
    pub exchange_rate_basis: Option<String>,
    pub exchange_rate_date: Option<String>,
    pub foreign_price: Option<f64>,
    pub discount_type: Option<String>,
    pub discount_value: Option<f64>,
    pub discount_amount: Option<f64>,
    pub foreign_discount_amount: Option<f64>,
    pub tax_id: Option<String>,
    pub tax_name: Option<String>,
    pub tax_code: Option<String>,
    pub tax_rate: Option<f64>,
    pub tax_calculation_mode: Option<String>,
    pub tax_base_amount: Option<f64>,
    pub foreign_tax_base_amount: Option<f64>,
    pub tax_amount: Option<f64>,
    pub foreign_tax_amount: Option<f64>,
    pub subtotal: Option<f64>,
    pub foreign_subtotal: Option<f64>,
    pub total_amount: Option<f64>,
    pub foreign_total_amount: Option<f64>,
    pub purchase_price: Option<f64>,
    pub original_price: Option<f64>,
    pub is_price_edited: Option<bool>,
    pub price_edited_by: Option<String>,
    pub price_edited_at: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesDocumentBundleDto {
    pub document: SalesDocumentDto,
    pub items: Vec<SalesDocumentItemDto>,
}
