use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct TransactionDto {
    pub id: String,
    pub transaction_number: String,
    pub business_type: Option<String>,
    pub cashier_session_id: Option<String>,
    pub cashier_session_number: Option<String>,
    pub restaurant_session_id: Option<String>,
    pub restaurant_session_number: Option<String>,
    pub restaurant_order_id: Option<String>,
    pub cashier_user_id: Option<String>,
    pub cashier_user_name: Option<String>,
    pub member_contact_id: Option<String>,
    pub member_id: Option<String>,
    pub member_number: Option<String>,
    pub member_name: Option<String>,
    pub member_phone: Option<String>,
    pub membership_points_earned: Option<f64>,
    pub membership_points_redeemed: Option<f64>,
    pub membership_point_discount_amount: Option<f64>,
    pub membership_points_balance_after: Option<f64>,
    pub subtotal_amount: Option<f64>,
    pub discount_amount: Option<f64>,
    pub discount_breakdown: Option<serde_json::Value>,
    pub applied_promos_snapshot: Option<serde_json::Value>,
    pub total_amount: f64,
    pub payment_amount: f64,
    pub change_amount: f64,
    pub payment_mode: Option<String>,
    pub payment_method: String,
    pub payment_method_id: Option<String>,
    pub payment_method_code: Option<String>,
    pub payment_method_name: Option<String>,
    pub payment_method_category: Option<String>,
    pub payment_reference: Option<String>,
    pub payment_posting_account_id: Option<String>,
    pub payment_posting_account_code: Option<String>,
    pub payment_posting_account_name: Option<String>,
    pub status: Option<String>,
    pub voided_at: Option<DateTime<Utc>>,
    pub void_reason: Option<String>,
    pub receipt_status: Option<String>,
    pub receipt_printed_at: Option<DateTime<Utc>>,
    pub receipt_print_error: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct TransactionItemDto {
    pub id: String,
    pub transaction_id: String,
    pub product_id: String,
    pub product_name: String,
    pub price: f64,
    pub selling_price: Option<f64>,
    pub original_price: Option<f64>,
    pub is_price_edited: Option<bool>,
    pub price_edited_by: Option<String>,
    pub price_edited_at: Option<DateTime<Utc>>,
    pub purchase_price: f64,
    pub quantity: f64,
    pub unit: String,
    pub unit_id: Option<String>,
    pub unit_label: Option<String>,
    pub unit_category: Option<String>,
    pub conversion_value: Option<f64>,
    pub base_unit: Option<String>,
    pub price_before_discount: Option<f64>,
    pub subtotal_before_discount: Option<f64>,
    pub discount_amount: Option<f64>,
    pub subtotal: f64,
    pub profit: f64,
    pub hpp_status: Option<String>,
    pub hpp_reconciled_at: Option<DateTime<Utc>>,
    pub hpp_variance_amount: Option<f64>,
    pub profit_status: Option<String>,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TransactionBundleDto {
    pub transaction: TransactionDto,
    pub items: Vec<TransactionItemDto>,
}
