/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportIndexRouteImport } from './routes/report/index'

const UnitsLazyRouteImport = createFileRoute('/units')()
const TransactionLazyRouteImport = createFileRoute('/transaction')()
const StockLazyRouteImport = createFileRoute('/stock')()
const ShoppingNoteLazyRouteImport = createFileRoute('/shopping-note')()
const SettingsLazyRouteImport = createFileRoute('/settings')()
const ProfitLazyRouteImport = createFileRoute('/profit')()
const HistoryLazyRouteImport = createFileRoute('/history')()
const FinanceLazyRouteImport = createFileRoute('/finance')()
const SplatLazyRouteImport = createFileRoute('/$')()
const ReportSalesReportLazyRouteImport = createFileRoute(
  '/report/sales-report',
)()
const ReportPurchaseReportLazyRouteImport = createFileRoute(
  '/report/purchase-report',
)()
const ReportExpenseReportLazyRouteImport = createFileRoute(
  '/report/expense-report',
)()

const UnitsLazyRoute = UnitsLazyRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/units.lazy').then((d) => d.Route))
const TransactionLazyRoute = TransactionLazyRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transaction.lazy').then((d) => d.Route))
const StockLazyRoute = StockLazyRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/stock.lazy').then((d) => d.Route))
const ShoppingNoteLazyRoute = ShoppingNoteLazyRouteImport.update({
  id: '/shopping-note',
  path: '/shopping-note',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/shopping-note.lazy').then((d) => d.Route))
const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const ProfitLazyRoute = ProfitLazyRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/profit.lazy').then((d) => d.Route))
const HistoryLazyRoute = HistoryLazyRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))
const FinanceLazyRoute = FinanceLazyRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/finance.lazy').then((d) => d.Route))
const SplatLazyRoute = SplatLazyRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportIndexRoute = ReportIndexRouteImport.update({
  id: '/report/',
  path: '/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSalesReportLazyRoute = ReportSalesReportLazyRouteImport.update({
  id: '/report/sales-report',
  path: '/report/sales-report',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/report/sales-report.lazy').then((d) => d.Route),
)
const ReportPurchaseReportLazyRoute =
  ReportPurchaseReportLazyRouteImport.update({
    id: '/report/purchase-report',
    path: '/report/purchase-report',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/report/purchase-report.lazy').then((d) => d.Route),
  )
const ReportExpenseReportLazyRoute = ReportExpenseReportLazyRouteImport.update({
  id: '/report/expense-report',
  path: '/report/expense-report',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/report/expense-report.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/history': typeof HistoryLazyRoute
  '/profit': typeof ProfitLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/shopping-note': typeof ShoppingNoteLazyRoute
  '/stock': typeof StockLazyRoute
  '/transaction': typeof TransactionLazyRoute
  '/units': typeof UnitsLazyRoute
  '/report/expense-report': typeof ReportExpenseReportLazyRoute
  '/report/purchase-report': typeof ReportPurchaseReportLazyRoute
  '/report/sales-report': typeof ReportSalesReportLazyRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/history': typeof HistoryLazyRoute
  '/profit': typeof ProfitLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/shopping-note': typeof ShoppingNoteLazyRoute
  '/stock': typeof StockLazyRoute
  '/transaction': typeof TransactionLazyRoute
  '/units': typeof UnitsLazyRoute
  '/report/expense-report': typeof ReportExpenseReportLazyRoute
  '/report/purchase-report': typeof ReportPurchaseReportLazyRoute
  '/report/sales-report': typeof ReportSalesReportLazyRoute
  '/report': typeof ReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/finance': typeof FinanceLazyRoute
  '/history': typeof HistoryLazyRoute
  '/profit': typeof ProfitLazyRoute
  '/settings': typeof SettingsLazyRoute
  '/shopping-note': typeof ShoppingNoteLazyRoute
  '/stock': typeof StockLazyRoute
  '/transaction': typeof TransactionLazyRoute
  '/units': typeof UnitsLazyRoute
  '/report/expense-report': typeof ReportExpenseReportLazyRoute
  '/report/purchase-report': typeof ReportPurchaseReportLazyRoute
  '/report/sales-report': typeof ReportSalesReportLazyRoute
  '/report/': typeof ReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/finance'
    | '/history'
    | '/profit'
    | '/settings'
    | '/shopping-note'
    | '/stock'
    | '/transaction'
    | '/units'
    | '/report/expense-report'
    | '/report/purchase-report'
    | '/report/sales-report'
    | '/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/finance'
    | '/history'
    | '/profit'
    | '/settings'
    | '/shopping-note'
    | '/stock'
    | '/transaction'
    | '/units'
    | '/report/expense-report'
    | '/report/purchase-report'
    | '/report/sales-report'
    | '/report'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/finance'
    | '/history'
    | '/profit'
    | '/settings'
    | '/shopping-note'
    | '/stock'
    | '/transaction'
    | '/units'
    | '/report/expense-report'
    | '/report/purchase-report'
    | '/report/sales-report'
    | '/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatLazyRoute: typeof SplatLazyRoute
  FinanceLazyRoute: typeof FinanceLazyRoute
  HistoryLazyRoute: typeof HistoryLazyRoute
  ProfitLazyRoute: typeof ProfitLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
  ShoppingNoteLazyRoute: typeof ShoppingNoteLazyRoute
  StockLazyRoute: typeof StockLazyRoute
  TransactionLazyRoute: typeof TransactionLazyRoute
  UnitsLazyRoute: typeof UnitsLazyRoute
  ReportExpenseReportLazyRoute: typeof ReportExpenseReportLazyRoute
  ReportPurchaseReportLazyRoute: typeof ReportPurchaseReportLazyRoute
  ReportSalesReportLazyRoute: typeof ReportSalesReportLazyRoute
  ReportIndexRoute: typeof ReportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/units': {
      id: '/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof UnitsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction': {
      id: '/transaction'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof TransactionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-note': {
      id: '/shopping-note'
      path: '/shopping-note'
      fullPath: '/shopping-note'
      preLoaderRoute: typeof ShoppingNoteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/': {
      id: '/report/'
      path: '/report'
      fullPath: '/report/'
      preLoaderRoute: typeof ReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/sales-report': {
      id: '/report/sales-report'
      path: '/report/sales-report'
      fullPath: '/report/sales-report'
      preLoaderRoute: typeof ReportSalesReportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/purchase-report': {
      id: '/report/purchase-report'
      path: '/report/purchase-report'
      fullPath: '/report/purchase-report'
      preLoaderRoute: typeof ReportPurchaseReportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/expense-report': {
      id: '/report/expense-report'
      path: '/report/expense-report'
      fullPath: '/report/expense-report'
      preLoaderRoute: typeof ReportExpenseReportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatLazyRoute: SplatLazyRoute,
  FinanceLazyRoute: FinanceLazyRoute,
  HistoryLazyRoute: HistoryLazyRoute,
  ProfitLazyRoute: ProfitLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
  ShoppingNoteLazyRoute: ShoppingNoteLazyRoute,
  StockLazyRoute: StockLazyRoute,
  TransactionLazyRoute: TransactionLazyRoute,
  UnitsLazyRoute: UnitsLazyRoute,
  ReportExpenseReportLazyRoute: ReportExpenseReportLazyRoute,
  ReportPurchaseReportLazyRoute: ReportPurchaseReportLazyRoute,
  ReportSalesReportLazyRoute: ReportSalesReportLazyRoute,
  ReportIndexRoute: ReportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
