/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const TransactionLazyRouteImport = createFileRoute('/transaction')()
const StockLazyRouteImport = createFileRoute('/stock')()
const SalesReportLazyRouteImport = createFileRoute('/sales-report')()
const PurchaseReportLazyRouteImport = createFileRoute('/purchase-report')()
const HistoryLazyRouteImport = createFileRoute('/history')()
const SplatLazyRouteImport = createFileRoute('/$')()

const TransactionLazyRoute = TransactionLazyRouteImport.update({
  id: '/transaction',
  path: '/transaction',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transaction.lazy').then((d) => d.Route))
const StockLazyRoute = StockLazyRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/stock.lazy').then((d) => d.Route))
const SalesReportLazyRoute = SalesReportLazyRouteImport.update({
  id: '/sales-report',
  path: '/sales-report',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/sales-report.lazy').then((d) => d.Route))
const PurchaseReportLazyRoute = PurchaseReportLazyRouteImport.update({
  id: '/purchase-report',
  path: '/purchase-report',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/purchase-report.lazy').then((d) => d.Route),
)
const HistoryLazyRoute = HistoryLazyRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))
const SplatLazyRoute = SplatLazyRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/history': typeof HistoryLazyRoute
  '/purchase-report': typeof PurchaseReportLazyRoute
  '/sales-report': typeof SalesReportLazyRoute
  '/stock': typeof StockLazyRoute
  '/transaction': typeof TransactionLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/history': typeof HistoryLazyRoute
  '/purchase-report': typeof PurchaseReportLazyRoute
  '/sales-report': typeof SalesReportLazyRoute
  '/stock': typeof StockLazyRoute
  '/transaction': typeof TransactionLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatLazyRoute
  '/history': typeof HistoryLazyRoute
  '/purchase-report': typeof PurchaseReportLazyRoute
  '/sales-report': typeof SalesReportLazyRoute
  '/stock': typeof StockLazyRoute
  '/transaction': typeof TransactionLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/history'
    | '/purchase-report'
    | '/sales-report'
    | '/stock'
    | '/transaction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/history'
    | '/purchase-report'
    | '/sales-report'
    | '/stock'
    | '/transaction'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/history'
    | '/purchase-report'
    | '/sales-report'
    | '/stock'
    | '/transaction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatLazyRoute: typeof SplatLazyRoute
  HistoryLazyRoute: typeof HistoryLazyRoute
  PurchaseReportLazyRoute: typeof PurchaseReportLazyRoute
  SalesReportLazyRoute: typeof SalesReportLazyRoute
  StockLazyRoute: typeof StockLazyRoute
  TransactionLazyRoute: typeof TransactionLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaction': {
      id: '/transaction'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof TransactionLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-report': {
      id: '/sales-report'
      path: '/sales-report'
      fullPath: '/sales-report'
      preLoaderRoute: typeof SalesReportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-report': {
      id: '/purchase-report'
      path: '/purchase-report'
      fullPath: '/purchase-report'
      preLoaderRoute: typeof PurchaseReportLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatLazyRoute: SplatLazyRoute,
  HistoryLazyRoute: HistoryLazyRoute,
  PurchaseReportLazyRoute: PurchaseReportLazyRoute,
  SalesReportLazyRoute: SalesReportLazyRoute,
  StockLazyRoute: StockLazyRoute,
  TransactionLazyRoute: TransactionLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
